const classes =
{
    ARROW               : `flounder__arrow--wrapper`,
    ARROW_INNER         : `flounder__arrow--inner`,
    DESCRIPTION         : `flounder__option--description`,
    DISABLED            : `flounder__disabled`,
    DISABLED_OPTION     : `flounder__disabled--option`,
    HEADER              : `flounder__header`,
    HIDDEN              : `flounder--hidden`,
    HIDDEN_IOS          : `flounder--hidden--ios`,
    HOVER               : `flounder__hover`,
    LIST                : `flounder__list`,
    LOADING             : `flounder__loading`,
    LOADING_FAILED      : `flounder__loading--failed`,
    MAIN                : `flounder`,
    MAIN_WRAPPER        : `flounder--wrapper  flounder__input--select`,
    MULTI_TAG_LIST      : `flounder__multi--tag--list`,
    MULTIPLE_SELECT_TAG : `flounder__multiple--select--tag`,
    MULTIPLE_TAG_CLOSE  : `flounder__multiple__tag__close`,
    OPEN                : `open`,
    OPTION              : `flounder__option`,
    OPTION_TAG          : `flounder--option--tag`,
    OPTIONS_WRAPPER     : `flounder__list--wrapper`,
    PLACEHOLDER         : `flounder__placeholder`,
    PLUG                : `flounder__ios--plug`,
    SECTION             : `flounder__section`,
    SELECTED            : `flounder__option--selected`,
    SELECTED_HIDDEN     : `flounder__option--selected--hidden`,
    SELECTED_DISPLAYED  : `flounder__option--selected--displayed`,
    SEARCH              : `flounder__input--search`,
    SEARCH_HIDDEN       : `flounder--search--hidden`,
    SELECT_TAG          : `flounder--select--tag`
};

export default classes;
